"""remove clomun creator

Revision ID: 14b797bf63c5
Revises: ed0aa8d60597
Create Date: 2025-08-15 20:07:10.400240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '14b797bf63c5'
down_revision: Union[str, Sequence[str], None] = 'ed0aa8d60597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_creators_category_id_categories'), 'creators', type_='foreignkey')
    op.drop_column('creators', 'country_code')
    op.drop_column('creators', 'category_id')
    op.drop_column('creators', 'tax_info')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('creators', sa.Column('tax_info', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('creators', sa.Column('category_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('creators', sa.Column('country_code', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('fk_creators_category_id_categories'), 'creators', 'categories', ['category_id'], ['id'])
    # ### end Alembic commands ###
