"""rename clomun table media_rendition_jobs

Revision ID: 19979c34ffe7
Revises: 4164700774d8
Create Date: 2025-09-01 01:24:00.702132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19979c34ffe7'
down_revision: Union[str, Sequence[str], None] = '4164700774d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_rendition_jobs', 'rendition_id',
               existing_type=sa.UUID(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_rendition_jobs', 'rendition_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
