"""add table media_rendition_jobs

Revision ID: 4164700774d8
Revises: eab474da0828
Create Date: 2025-08-30 20:09:18.598731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4164700774d8'
down_revision: Union[str, Sequence[str], None] = 'eab474da0828'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('media_rendition_jobs',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('asset_id', sa.UUID(), nullable=False),
    sa.Column('rendition_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.SmallInteger(), nullable=False),
    sa.Column('backend', sa.SmallInteger(), nullable=False),
    sa.Column('status', sa.SmallInteger(), nullable=False),
    sa.Column('input_key', sa.Text(), nullable=False),
    sa.Column('output_prefix', sa.Text(), nullable=True),
    sa.Column('output_key', sa.Text(), nullable=True),
    sa.Column('job_id', sa.Text(), nullable=True),
    sa.Column('percent_complete', sa.SmallInteger(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('master_manifest_key', sa.Text(), nullable=True),
    sa.Column('extra', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['media_assets.id'], name=op.f('fk_media_rendition_jobs_asset_id_media_assets'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['rendition_id'], ['media_renditions.id'], name=op.f('fk_media_rendition_jobs_rendition_id_media_renditions'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_rendition_jobs'))
    )
    op.create_index(op.f('ix_media_rendition_jobs_asset_id'), 'media_rendition_jobs', ['asset_id'], unique=False)
    op.create_index(op.f('ix_media_rendition_jobs_rendition_id'), 'media_rendition_jobs', ['rendition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_media_rendition_jobs_rendition_id'), table_name='media_rendition_jobs')
    op.drop_index(op.f('ix_media_rendition_jobs_asset_id'), table_name='media_rendition_jobs')
    op.drop_table('media_rendition_jobs')
    # ### end Alembic commands ###
