"""add clomoun cover_url plofile table

Revision ID: 489c94fb2c4c
Revises: 03ca0ef01074
Create Date: 2025-08-18 02:03:16.427692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '489c94fb2c4c'
down_revision: Union[str, Sequence[str], None] = '03ca0ef01074'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('cover_url', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'cover_url')
    # ### end Alembic commands ###
