"""add column post_type posts table

Revision ID: 4b6ee44d7feb
Revises: a429f16d854b
Create Date: 2025-09-12 12:37:46.403132

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b6ee44d7feb'
down_revision: Union[str, Sequence[str], None] = 'a429f16d854b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('post_type', sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'post_type')
    # ### end Alembic commands ###
