"""Fix users table id default to use gen_random_uuid

Revision ID: 5603d4262927
Revises: c0e4b5c269a2
Create Date: 2025-08-13 10:22:00.363605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5603d4262927'
down_revision: Union[str, Sequence[str], None] = 'c0e4b5c269a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id', server_default=sa.text('gen_random_uuid()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'id', server_default=None)
    # ### end Alembic commands ###
