"""create preregistrations table

Revision ID: 984feb5600e2
Revises: 6656ea5056dc
Create Date: 2025-09-29 23:23:46.279640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '984feb5600e2'
down_revision: Union[str, Sequence[str], None] = '6656ea5056dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('preregistrations',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('x_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_preregistrations')),
    sa.UniqueConstraint('email', name=op.f('uq_preregistrations_email'))
    )
    op.drop_constraint(op.f('uq_profiles_display_name'), 'profiles', type_='unique')
    op.create_unique_constraint(op.f('uq_profiles_username'), 'profiles', ['username'])
    op.drop_constraint(op.f('uq_users_slug'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_profile_name'), 'users', ['profile_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_users_profile_name'), 'users', type_='unique')
    op.create_unique_constraint(op.f('uq_users_slug'), 'users', ['profile_name'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_profiles_username'), 'profiles', type_='unique')
    op.create_unique_constraint(op.f('uq_profiles_display_name'), 'profiles', ['username'], postgresql_nulls_not_distinct=False)
    op.drop_table('preregistrations')
    # ### end Alembic commands ###
