"""change column  name description plan table 

Revision ID: 9dff762da0d0
Revises: 14fe4c3de41d
Create Date: 2025-08-27 19:36:01.260156

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dff762da0d0'
down_revision: Union[str, Sequence[str], None] = '14fe4c3de41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('plans', 'name',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('posts', 'description',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('posts', 'description',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('plans', 'name',
               existing_type=sa.TEXT(),
               nullable=False)
    # ### end Alembic commands ###
