"""add column ogp_storage_key posts table

Revision ID: b0ce1f7869a8
Revises: c5ecd9d67d90
Create Date: 2025-08-28 00:48:19.832514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b0ce1f7869a8'
down_revision: Union[str, Sequence[str], None] = 'c5ecd9d67d90'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('ogp_storage_key', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('sample_video_storage_key', sa.Text(), nullable=True))
    op.add_column('posts', sa.Column('sample_video_duration', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'sample_video_duration')
    op.drop_column('posts', 'sample_video_storage_key')
    op.drop_column('posts', 'ogp_storage_key')
    # ### end Alembic commands ###
