"""change column name description plan price table and reration price plan

Revision ID: c5ecd9d67d90
Revises: 9dff762da0d0
Create Date: 2025-08-27 20:58:40.898718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5ecd9d67d90'
down_revision: Union[str, Sequence[str], None] = '9dff762da0d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plans', sa.Column('type', sa.SmallInteger(), nullable=False))
    op.drop_column('plans', 'billing_cycle')
    op.drop_column('plans', 'price')
    op.drop_column('plans', 'currency')
    op.add_column('prices', sa.Column('status', sa.SmallInteger(), nullable=False))
    op.add_column('prices', sa.Column('price', sa.BigInteger(), nullable=False))
    op.drop_column('prices', 'unit_amount')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('unit_amount', sa.BIGINT(), autoincrement=False, nullable=False))
    op.drop_column('prices', 'price')
    op.drop_column('prices', 'status')
    op.add_column('plans', sa.Column('currency', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('price', sa.BIGINT(), autoincrement=False, nullable=False))
    op.add_column('plans', sa.Column('billing_cycle', sa.SMALLINT(), autoincrement=False, nullable=False))
    op.drop_column('plans', 'type')
    # ### end Alembic commands ###
