"""remove key column  post  table and add cloumn media_assets

Revision ID: eab474da0828
Revises: b0ce1f7869a8
Create Date: 2025-08-30 19:04:24.114628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab474da0828'
down_revision: Union[str, Sequence[str], None] = 'b0ce1f7869a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('kind', sa.SmallInteger(), nullable=False))
    op.drop_column('media_assets', 'storage_bucket')
    op.drop_column('posts', 'video_storage_key')
    op.drop_column('posts', 'sample_video_storage_key')
    op.drop_column('posts', 'sample_video_duration')
    op.drop_column('posts', 'video_duration')
    op.drop_column('posts', 'ogp_storage_key')
    op.drop_column('posts', 'thumbnail_storage_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('thumbnail_storage_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('ogp_storage_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('video_duration', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('sample_video_duration', sa.BIGINT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('sample_video_storage_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('posts', sa.Column('video_storage_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('media_assets', sa.Column('storage_bucket', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('media_assets', 'kind')
    # ### end Alembic commands ###
