"""rename clomoun dispaly_name plofile  table

Revision ID: ee6af6feb2fc
Revises: 489c94fb2c4c
Create Date: 2025-08-18 18:08:57.744158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ee6af6feb2fc'
down_revision: Union[str, Sequence[str], None] = '489c94fb2c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('profiles', 'display_name',
               existing_type=sa.TEXT(),
               type_=postgresql.CITEXT(),
               existing_nullable=True)
    op.create_unique_constraint(op.f('uq_profiles_display_name'), 'profiles', ['display_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_profiles_display_name'), 'profiles', type_='unique')
    op.alter_column('profiles', 'display_name',
               existing_type=postgresql.CITEXT(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
